language: scala

before_install:
  - sudo git clone --depth 1 --branch release https://github.com/adobe-fonts/source-code-pro.git /usr/share/fonts/source-code-pro
  - sudo rm -rf /usr/share/fonts/source-code-pro/.git
  - fc-cache -f -v /usr/share/fonts/source-code-pro

addons:
  apt:
    packages:
    - graphviz

script: sbt +clean +test

deploy:
  provider: script
  script: sbt +publishSigned sonatypeReleaseAll
  on:
    tags: true
